### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\hatot\.vscode\vtuberdule\.next\BUILD_ID'

### ISSUE THREAD

**Issue by hato72** [hato72/vtuberdule#1]
$ npm startをした際に以下のエラーが出た

Error: ENOENT: no such file or directory, open 'C:\Users\hatot\.vscode\vtuberdule\.next\BUILD_ID'
    at async open (node:internal/fs/promises:636:25)
    at async Object.readFile (node:internal/fs/promises:1246:14)
    at async setupFsCheck (C:\Users\hatot\.vscode\vtuberdule\node_modules\next\dist\server\lib\router-utils\filesystem.js:145:19)
    at async initialize (C:\Users\hatot\.vscode\vtuberdule\node_modules\next\dist\server\lib\router-server.js:62:23)
    at async Server.<anonymous> (C:\Users\hatot\.vscode\vtuberdule\node_modules\next\dist\server\lib\start-server.js:247:36) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\hatot\\.vscode\\vtuberdule\\.next\\BUILD_ID'
}

**Comment by hato72** [comment]
解決法：
以下を順に実行する
npm uninstall next
npm install next
npm run build 
npm run start
